#%RAML 1.0 NamedExample

complaints:
  -
    complaintNumber: 1000
    complaintDescription: broken headphones
    active: true
    customerDetails:
      customerNumber: 001
      customerName: veenayak    
      customerEmail: dungeon8888@gmail.com   
    orderDetails: 
        orderId: 10001
        orderDate: 1992-01-20
    productDetails: 
        productId: P1001
        productName: beats headset
        productCost: 1000